name: .NET

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore TakiFight.Tests/TakiFight.Tests.csproj
      - name: Run tests
        run: dotnet test TakiFight.Tests/TakiFight.Tests.csproj --collect:"XPlat Code Coverage"
      - name: Upload coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage-results
          path: '**/TestResults/**'
