name: Post Update Log

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  send-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      - name: Send changelog entry
        env:
          PLAYTEST_DISCORD_UPDATE: ${{ secrets.PLAYTEST_DISCORD_UPDATE }}
        run: bash scripts/send_update_log.sh
