name: Unity Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform: [StandaloneWindows64, StandaloneLinux64]
    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          unityVersion: 6000.0.28f1
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.targetPlatform }}-build
          path: build/${{ matrix.targetPlatform }}
      - name: Notify Discord
        if: success()
        env:
          PLAYTEST_DISCORD_BUILD: ${{ secrets.PLAYTEST_DISCORD_BUILD }}
        run: |
          curl -H "Content-Type: application/json" \
            -d "{\"content\":\"New build for ${{ matrix.targetPlatform }}: https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/${{ matrix.targetPlatform }}-build.zip\"}" \
            $PLAYTEST_DISCORD_BUILD
