name: Unity Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform: [StandaloneWindows64, StandaloneLinux64]
    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          unityVersion: 6000.0.28f1
          targetPlatform: ${{ matrix.targetPlatform }}
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.targetPlatform }}-build
          path: build/${{ matrix.targetPlatform }}
      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone
      - name: Upload to Drive
        env:
          DRIVE_SERVICE_ACCOUNT_KEY: ${{ secrets.DRIVE_SERVICE_ACCOUNT_KEY }}
          DRIVE_BUILD_FOLDER: ${{ secrets.DRIVE_BUILD_FOLDER }}
        run: |
          echo "$DRIVE_SERVICE_ACCOUNT_KEY" > service-account.json
          rclone config create buildremote drive service_account_file service-account.json --config rclone.conf
          rclone copy "build/${{ matrix.targetPlatform }}" buildremote:"$DRIVE_BUILD_FOLDER"/${{ matrix.targetPlatform }} --config rclone.conf --create-empty-src-dirs
      - name: Notify Discord
        if: success()
        env:
          PLAYTEST_DISCORD_BUILD: ${{ secrets.PLAYTEST_DISCORD_BUILD }}
          DRIVE_BUILD_FOLDER: ${{ secrets.DRIVE_BUILD_FOLDER }}
        run: |
          ARTIFACT_LINK="https://nightly.link/${{ github.repository }}/actions/runs/${{ github.run_id }}/${{ matrix.targetPlatform }}-build.zip"
          DRIVE_LINK="https://drive.google.com/drive/folders/$DRIVE_BUILD_FOLDER"
          curl -H "Content-Type: application/json" \
            -d "{\"content\":\"New build for ${{ matrix.targetPlatform }}:\nArtifact: $ARTIFACT_LINK\nDrive: $DRIVE_LINK\"}" \
            $PLAYTEST_DISCORD_BUILD
